services:
  blog-database:
    image: mongo
    ports:
      - '27017:27017'
  blog-backend:
    build: backend/
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb+srv://MotherMonster:TuF5DjemNNFw8bFl@fullstackmongotutorial.exjwy.mongodb.net/?retryWrites=true&w=majority&appName=fullStackMongoTutorial
    ports:
      - '3001:3001'
    depends_on:
      - blog-database
  blog-frontend:
    build:
      context: .
      args:
        VITE_BACKEND_URL: https://blog-backend-886172233725.us-west1.run.app/api/v1
    ports:
      - '3000:80'
    depends_on:
      - blog-backend
